### ISSUE TITLE
Warning: php.ini: upload_max_filesize (40) set lower than MAX_FILESIZE (953)

### ISSUE THREAD

**Issue by finn1476** [Rouji/single_php_filehost#16]
Hey i have a small problem i am trying to change the Maximum Filesize but i just get that error and i cant find the option to change upload_max_filesize

**Comment by Rouji** [comment]
Kind of depends on your distro and stuff, but usually it's in your php.ini somewhere in /etc. `grep -r upload_max_filesize /etc/php*` should find something

**Comment by finn1476** [comment]
Thanks
