### ISSUE TITLE
Apache Directory

### ISSUE THREAD

**Issue by Hansat1** [Rouji/single_php_filehost#17]
Hey, I am trying to add to the Apache Directory a site but I can't get it right working.
I tried it like that.
<Directory C:\xampp\htdocs>
    Options +FollowSymLinks -MultiViews -Indexes
    AddDefaultCharset UTF-8
    AllowOverride None

    RewriteEngine On
    RewriteCond "%{ENV:REDIRECT_STATUS}" "^$"
    RewriteRule "^/?$" "index.php" [L,END]
    RewriteRule "^/?$" "takedown.php" [L,END]
    RewriteRule "^(.+)$" "files/$1" [L,END]
</Directory>

<Directory C:\xampp\htdocs\files>
    Options -ExecCGI
    php_flag engine off
    SetHandler None
    AddType text/plain .php .php5 .html .htm .cpp .c .h .sh
</Directory>
I i try accessing the link it only redirects it to a 404 Page

**Comment by Rouji** [comment]
Could you fix your coypasted code there? Can't really tell what you're doing wrong otherwise.

**Comment by Hansat1** [comment]
The links worked before I added the Directory in the apache httpd.conf file.
echo <<<EOT
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Fileron</title>
    <meta name="description" content="Minimalistic service for sharing files." />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" type="text/css" href="styles.css" />
</head>
<body>
<nav>
<a href="index.php" a>HOME  </a>
<a href="takedown.php" a>ABUSE  </a>
<a href="info.php" a>INFORMATION  </a>
<a href="source.php" a>SOURCE  </a>
</nav>
<main>




<h1 class="title">Fileron</h1>
<pre>
<class="datei" span>
</pre>
<form id="Fileron" method="post" enctype="multipart/form-data">
<input type="file" name="file" id="file" />
<input type="hidden" name="formatted" value="true" />
<input type="submit" value="Upload"/>
</form>
<pre>
</span>

 




 
</pre>
</main>
<footer>
<a href="#" a>IMPRESUM  </a>
</footer>
</body>
</html>
EOT;

**Comment by Rouji** [comment]
What.

...are you having problems with /takedown.php etc. not working? Is that what you're asking?

**Comment by Hansat1** [comment]
My problem is after adding the Directory Text to the XAMPP httpd.conf file the links on the website no longer works and without it they work again

**Comment by Rouji** [comment]
You're doing the RewriteRule wrong. You're matching `^/?$` twice, meaning second one is always ignored. (And is also incorrect for what you're trying to do)

Here's a working example:
```
        RewriteCond "%{ENV:REDIRECT_STATUS}" "^$"
        RewriteRule "^/?favicon.ico$" "favicon.ico" [L,END]
        RewriteRule "^/?robots.txt$" "robots.txt" [L,END]
        RewriteRule "^/?$" "index.php" [L,END]
        RewriteRule "^(.+)$" "files/$1" [L,END]
```

**Comment by Hansat1** [comment]
What woud be correct for what i am trying to do?

**Comment by Rouji** [comment]
I even gave you an example. Please use your own head. 
If you can't even figure that out, you're frankly not ready to host a public filesharing site.
