### ISSUE TITLE
MIME block

### ISSUE THREAD

**Issue by jamalewd** [Rouji/single_php_filehost#18]
how to block .php .apk files?

**Comment by Rouji** [comment]
Not really documented well, but you can use the EXTERNAL_HOOK

**Comment by jamalewd** [comment]
> 

how to use it? I don't really understand

const EXTERNAL_HOOK = null; //external program to call for each upload
    const AUTO_FILE_EXT = false; //automatically try to detect file extension for files that have none

**Comment by Rouji** [comment]
You can put a path to an executable in there, that'll get called for every upload. Just have a look at the code around line 150

**Comment by Rouji** [comment]
Configure your webserver so it doesn't handle any files but index.php as executable.
