### ISSUE TITLE
VirusTotal reports x0.at as malware

### ISSUE THREAD

**Issue by AdriandMartin** [Rouji/single_php_filehost#22]
I open this issue because x0.at [is flagged as malware](https://www.virustotal.com/gui/url/4f1cd0652bb037ae28f4f6c8d43adb207d4c2ef38abc280d700799f53dc64cf5) in VirusTotal by one of its security vendors. It took me a long time to find this repository and convince myself that the service is legitimate, so I consider important to fix this so that potential new users can trust the website

**Comment by Rouji** [comment]
Only one false positive out of that long list sounds ok to me tbh.
