### ISSUE TITLE
Add an option for longer file keys

### ISSUE THREAD

**Issue by alexlehm** [Rouji/single_php_filehost#25]
Could you add an option secret= to make the file key longer to make it unguessable if you want to post almost hidden information.

**Comment by Rouji** [comment]
Do you want that for your instance of this, or on x0.at? Because I don't really want to pretend putting sensitive stuff on x0.at is a good idea🤔

**Comment by alexlehm** [comment]
I agree that it should not be used for really sensitive stuff, more to post something that is not found immediately.

I would think having an option to turn that on and off would be fine. I patched it into my own instance for now.

**Comment by Rouji** [comment]
I guess adding a `name_length=N` parameter or something wouldn't be too problematic. PR would be neat, or I'll do it in a few blue moons when I have time for stuff again.

I wouldn't say files can be found "immediately" though, the keyspace is quite a few orders of magnitude larger than the number of files on x0.at

**Comment by alexlehm** [comment]
i will clean up my adhoc patch and submit it when i have time

**Comment by alexlehm** [comment]
created as #26
