### ISSUE TITLE
Security vulnerability responsible disclosure

### ISSUE THREAD

**Issue by lukigruszka** [Rouji/single_php_filehost#27]
Hello,

CERT PL found a security vulnerability in this repository. How can we report this privately? We don't see any security policy describing how such vulnerabilities should be reported.

**Comment by Rouji** [comment]
email me?

**Comment by Rouji** [comment]
(they never emailed me)

**Comment by lukigruszka** [comment]
Sorry for the late response, you should have received the email by now at a@r0.at
