### ISSUE TITLE
file lifetime

### ISSUE THREAD

**Issue by MalexTP** [Rouji/single_php_filehost#3]
Add something who tells u how much the file will be online before deleting, like "you file will be deleted in 45 days!" :P

**Comment by Rouji** [comment]
Add it where? 

(You do have all the values you need to calculate that yourself if you absolutely have to.)

**Comment by MalexTP** [comment]
in x0.at

Yes, I can calculate it, but you can add it as a little detail

Probably you can create an option in the source code to enable or disable that "feature"

**Comment by Rouji** [comment]
No, the question is where would I even display that?
The returned text is deliberately nothing but the link so you don't have to do any text manipulation after calling curl

**Comment by Juliaria08** [comment]
You cloud make an enpoint if you realy wanted but i think it is not worth it, like have a form for it where you put the url of the file

**Comment by Rouji** [comment]
> You cloud make an enpoint if you realy wanted but i think it is not worth it, like have a form for it where you put the url of the file

Yeah, nah. You're not supposed to really precisely depend on that anyway. The idea is "big file very short, small file very long". The full formula is only there almost as an FYI. A graph would probably help that a lot, but I've just not come up with a good one yet.
