### ISSUE TITLE
How can I configure the .htaccess for Webspace  

### ISSUE THREAD

**Issue by Askadelion** [Rouji/single_php_filehost#4]
When i use this, come an error:

```
<Directory /path/to/webroot/>
    Options +FollowSymLinks -MultiViews -Indexes
    AddDefaultCharset UTF-8
    AllowOverride None

    RewriteEngine On
    RewriteCond "%{ENV:REDIRECT_STATUS}" "^$"
    RewriteRule "^/?$" "index.php" [L,END]
    RewriteRule "^(.+)$" "files/$1" [L,END]
</Directory>
```

```
<Directory /path/to/webroot/files>
    Options -ExecCGI
    php_flag engine off
    SetHandler None
    AddType text/plain .php .php5 .html .htm .cpp .c .h .sh
</Directory>
```

I think is only for Apache Root Config or? How i Configure this for mod_rewrite, for a webspace Package?
Can everyone help me?

**Comment by Rouji** [comment]
The example config is already mostly rewrite...
What exactly are you having problems with?

**Comment by Askadelion** [comment]
i can only insert the htaccess in the folder from index root, i can not modify direkt the apache
```
files
.htaccess
index.php
```
when i make insert this come error:

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at service@webmailer.de to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

i have try modify so:

```
<IfModule mod_rewrite.c>
    Options +FollowSymLinks -MultiViews -Indexes
    AddDefaultCharset UTF-8
    AllowOverride None

    RewriteEngine On
    RewriteCond "%{ENV:REDIRECT_STATUS}" "^$"
    RewriteRule "^/?$" "index.php" [L,END]
    RewriteRule "^(.+)$" "files/$1" [L,END]
</IfModule>
```

but the same problem

**Comment by Rouji** [comment]
`AllowOverride` isn't allowed in .htaccess, I think.  
Also don't forget about the 'files' dir's config, or prepare to get pwned.

**Comment by Askadelion** [comment]
i have now use this; 
```
RewriteEngine On
RewriteRule "^/?$" "index.php" [L,END]
RewriteRule "^(.+)$" "files/$1" [L,END]

AddCharset UTF-8 .txt
```

Now running ur script

**Comment by Rouji** [comment]
👍

...you did configure the 'files' dir properly, right?

**Comment by Askadelion** [comment]
i don know if correct but the .htacces is not in the Files dir xDD, but ist run ^^"
i have only a one .htaccess in the root with follow lines 
```
RewriteEngine On
RewriteRule "^/?$" "index.php" [L,END]
RewriteRule "^(.+)$" "files/$1" [L,END]

AddCharset UTF-8 .txt
```

**Comment by Rouji** [comment]
That won't prevent people from uploading a .php file and abusing your server.

**Comment by Askadelion** [comment]
ahh i know what u mean, what i musst be change for it

**Comment by Rouji** [comment]
See example in README.

Please be aware that this thing is very easy to abuse if you don't know what you're doing.
(Also it seems like you're using some shared webhost, which probably won't be happy with you hosting this either)

**Comment by Askadelion** [comment]
i know, i have the ok from webhoster when i will use this ^^ but the spport from hoster for help is bad xD not really help

**Comment by Rouji** [comment]
That doesn't sound very reassuring.  
I wish you the best of luck anyway.
