### ISSUE TITLE
Extension block

### ISSUE THREAD

**Issue by Verdem-crypto** [Rouji/single_php_filehost#5]
How can I block the loading of files with certain extensions?

**Comment by Rouji** [comment]
The code doesn't do that (yet), but it would be fairly simple to implement. Feel free to send a PR if you do🙌

**Comment by Verdem-crypto** [comment]
Ok I will study it! Thanks😁

**Comment by Rouji** [comment]
This is doable now with the generic hook thingy: 8ff340afc9ab901714526370863350c37e75cbc2
