### ISSUE TITLE
Http error 520 after trying to upload

### ISSUE THREAD

**Issue by ShrekisLyf** [Rouji/single_php_filehost#6]
I tried to test if uploading works but the server throws back an error, I have the .htaccess file and enabled rewrite

I would really appreciate help

**Comment by Rouji** [comment]
Your webserver probably can't write to $STORE_PATH

**Comment by ShrekisLyf** [comment]
I forgot that I don't have set up chmod for any file/directory

**Comment by ShrekisLyf** [comment]
This was the issue
Thank you for telling me
